/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export type {
	AgentAvatar,
	AgentConfig,
	AgentDiscoveryResult,
	AgentHook,
	AgentHooks,
	AgentMode,
	AgentScope,
	AgentSource,
	AgentTier,
	PathConfig,
} from "./agent-types.ts";
export {
	discoverAgents,
	formatAgentList,
	formatAgentsForPrompt,
	getBuiltinAgents,
	loadAgentsFromDir,
} from "./agent-types.ts";
export {
	type AskPermissionOptions,
	type AskPermissionStore,
	askPermission,
} from "./ask-permission.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export type {
	ConnectionStatus,
	DiscoveredTool,
	McpConnection,
	McpManagerEvents,
	McpManagerOptions,
	McpServerConfig,
	McpSettings,
	McpSseServerConfig,
	McpStdioServerConfig,
	McpStreamableHttpServerConfig,
} from "./mcp/index.ts";
// MCP
export { McpManager } from "./mcp/index.ts";
export {
	createDangerousCommandProvider,
	createPathAccessProvider,
	createPiHooksProvider,
	createStoredDecisionProvider,
	createToolGateProvider,
	type DangerousCommandAction,
	type DangerousCommandPattern,
	type DangerousCommandProviderOptions,
	DEFAULT_DANGEROUS_COMMAND_PATTERNS,
	defaultStoredDecisionCandidates,
	findDangerousCommandMatch,
	inputToPermissionRecord,
	matchesAnyPathPattern,
	matchesToolPattern,
	matchPathGlob,
	normalizePermissionPath,
	type PathAccessProviderOptions,
	type PermissionAction,
	type PermissionContext,
	type PermissionDecision,
	type PermissionProvider,
	type PermissionProviderFailure,
	type PermissionRememberOption,
	type PermissionRequest,
	type PermissionRule,
	type PermissionRuleAction,
	type PermissionRuleDecision,
	type PermissionRuleInput,
	type PermissionRuleMatchInput,
	type PermissionRuleScope,
	PermissionRuntime,
	type PermissionRuntimeOptions,
	type PermissionSettings,
	PermissionStore,
	type PermissionStoreSettingsHost,
	type PiHooksProviderOptions,
	readPermissionRules,
	type StoredDecisionLookup,
	type StoredDecisionProviderOptions,
	type ToolGateProviderOptions,
} from "./permissions/index.ts";
export {
	clearSessionHooks,
	clearSessionHooksBySource,
	getAllSessionHookGroups,
	getSessionHookGroups,
	normalizeSessionHooks,
	type ParseSessionHooksResult,
	parseSessionHookHandler,
	parseSessionHooks,
	parseSessionHooksWithDiagnostics,
	registerSessionHooks,
	type SessionHookEntry,
	type SessionHookGroup,
	type SessionHookHandler,
	type SessionHookHandlerType,
	type SessionHookParseDiagnostic,
	type SessionHooks,
} from "./session-hooks.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
export {
	ExtensionStorage,
	encodeProjectPath,
	getCwdDataDir,
	getGlobalDataDir,
	getProjectDataDir,
	getSessionDataDir,
	resolveProjectIdentity,
	resolveProjectRoot,
	type StoragePaths,
} from "./storage.ts";
export {
	runSubtask,
	type SubtaskContext,
	type SubtaskOptions,
	type SubtaskResult,
} from "./subtask.ts";
